#!/bin/bash
# script to run track Mhe for a list of N_mhe

for i in {3..15}
do
python track_exc_RT.py $i
done
python track_excitations.py

for i in {3..25}
do
python track_exc_RT_act.py $i
done
python track_excitations_act.py

